export const cities = [
  'delhi', 'noida', 'gurgaon', 'faridabad', 'ghaziabad', 'greater-noida', 'dwarka',
  'gurugram', 'manesar', 'bahadurgarh', 'sonipat', 'rohtak', 'panipat', 'karnal',
  'rewari', 'bhiwadi', 'alwar', 'meerut', 'hapur', 'bulandshahr', 'modinagar',
  'mumbai', 'bangalore', 'hyderabad', 'chennai', 'kolkata', 'pune', 'ahmedabad',
  'surat', 'jaipur', 'lucknow', 'kanpur', 'nagpur', 'indore', 'bhopal',
  'patna', 'vadodara', 'ludhiana', 'agra', 'nashik', 'ranchi', 'coimbatore',
  'vijayawada', 'mysore', 'jodhpur', 'raipur', 'kochi', 'chandigarh',
  'bhubaneswar', 'thiruvananthapuram', 'visakhapatnam', 'madurai',
];

export type CityData = {
  area: string;
  tip: string;
  landmarks: string[];
  commonIssues: string[];
  priceNote: string;
  responseTime: string;
};

export const cityContent: Record<string, CityData> = {
  "delhi": {
    area: "South Delhi, West Delhi, East Delhi, Central Delhi",
    tip: "Delhi's extreme summer heat above 45°C degrades engine oil faster — switch to a higher viscosity oil in May-June.",
    landmarks: ["Connaught Place", "Lajpat Nagar", "Karol Bagh", "Dwarka Expressway"],
    commonIssues: ["Battery drain in peak summer", "Chain rust during monsoon", "Air filter clogging from smog", "Overheating in traffic jams"],
    priceNote: "No extra travel charge across all Delhi zones. Transparent pricing with GST included.",
    responseTime: "45-60 minutes across most Delhi areas",
  },
  "noida": {
    area: "Sector 18, Sector 62, Sector 120, Sector 137",
    tip: "Potholes on older Noida sector roads wear out suspension — get suspension checked every 5000km.",
    landmarks: ["Sector 18 Market", "Botanical Garden", "Noida Expressway", "DND Flyway"],
    commonIssues: ["Suspension damage from potholes", "Tyre punctures on construction zones", "Dust filter clogging", "Battery issues in winter"],
    priceNote: "Same pricing as Delhi — no Noida surcharge. Covers all sectors including Greater Noida border.",
    responseTime: "40-55 minutes across Noida sectors",
  },
  "gurgaon": {
    area: "DLF Phase 1-5, Sohna Road, Cyber City, Golf Course Road",
    tip: "Gurgaon's flyovers and heavy corporate traffic mean clutch plates wear faster — inspect every 8000km.",
    landmarks: ["Cyber Hub", "Ambience Mall", "Golf Course Road", "Sohna Road"],
    commonIssues: ["Clutch wear in stop-start traffic", "Brake fade on flyovers", "Tyre pressure loss in heat", "Electrical issues from waterlogging"],
    priceNote: "Covers all Gurgaon sectors and Manesar. Corporate area pickups available on same day.",
    responseTime: "45-70 minutes depending on sector",
  },
  "gurugram": {
    area: "DLF Phase 1-5, Sohna Road, Cyber City, Golf Course Road",
    tip: "Heavy corporate traffic in Gurugram means frequent clutch and brake inspections are essential.",
    landmarks: ["Cyber Hub", "Ambience Mall", "Udyog Vihar", "NH-48"],
    commonIssues: ["Clutch wear in heavy traffic", "Brake fade on flyovers", "Chain slipping", "Battery drain in summer"],
    priceNote: "Full coverage across Gurugram. No hidden charges for highway pickups.",
    responseTime: "45-70 minutes depending on location",
  },
  "faridabad": {
    area: "NIT, Sector 15, Old Faridabad, Ballabhgarh",
    tip: "Industrial dust on Faridabad roads clogs air filters twice as fast — clean every 1500km instead of 3000km.",
    landmarks: ["Crown Interiorz Mall", "Sector 15 Market", "Mathura Road", "Ballabhgarh Chowk"],
    commonIssues: ["Air filter clogging from industrial dust", "Tyre wear on rough roads", "Chain rust", "Overheating near industrial zones"],
    priceNote: "Covers NIT, Ballabhgarh, and all Faridabad sectors. Industrial area pickup available.",
    responseTime: "50-65 minutes across Faridabad",
  },
  "ghaziabad": {
    area: "Indirapuram, Vaishali, Raj Nagar, Kaushambi",
    tip: "Stop-and-go city riding in Ghaziabad means chains need lubrication every 500km and clutch checks every 6000km.",
    landmarks: ["Shipra Mall", "Raj Nagar Extension", "NH-58", "Hindon River Bridge"],
    commonIssues: ["Chain wear in congested traffic", "Clutch slipping", "Dust filter issues", "Tyre punctures on service roads"],
    priceNote: "Covers Indirapuram, Vaishali, Raj Nagar, and surrounding areas. No extra charge.",
    responseTime: "45-60 minutes across Ghaziabad",
  },
  "greater-noida": {
    area: "Omega, Alpha, Knowledge Park, Pari Chowk",
    tip: "Expressway high speeds require maintaining correct tyre pressure — check weekly and inflate to manufacturer spec.",
    landmarks: ["Pari Chowk", "Knowledge Park", "Yamuna Expressway", "Expo Mart"],
    commonIssues: ["Tyre blowouts at highway speed", "Suspension stress on expressway", "Battery drain in isolated sectors", "Brake wear on long rides"],
    priceNote: "Full coverage across all Greater Noida sectors including Yamuna Expressway corridor.",
    responseTime: "55-75 minutes from Delhi base",
  },
  "dwarka": {
    area: "Sector 10, Sector 12, Sector 21, Dwarka Expressway",
    tip: "Dusty winds in Dwarka from the Haryana border clog air filters and chains faster than other Delhi areas.",
    landmarks: ["Dwarka Sector 21 Metro", "Pacific Mall", "Dwarka Expressway", "Palam Airport Road"],
    commonIssues: ["Air filter clogging from dust", "Chain rusting in monsoon", "Tyre wear on expressway", "Battery issues in winter"],
    priceNote: "Covers all Dwarka sectors. Airport road and Expressway pickups available same day.",
    responseTime: "40-55 minutes across Dwarka sectors",
  },
  "manesar": {
    area: "IMT Manesar, Sector 4, Sector 8, NH-48",
    tip: "Industrial area dust in Manesar clogs air filters faster — service every 1500-2000km instead of standard intervals.",
    landmarks: ["IMT Manesar Industrial Area", "NH-48 Toll", "Maruti Suzuki Plant", "Sector 4 Market"],
    commonIssues: ["Heavy air filter clogging", "Engine overheating near factories", "Tyre punctures on industrial roads", "Chain rust from chemical exposure"],
    priceNote: "Industrial zone specialist. Factory shift-hour pickups available for workers.",
    responseTime: "50-65 minutes from Gurgaon base",
  },
  "bahadurgarh": {
    area: "Bahadurgarh City, Tikri Border, Asthal Bohar, NH-10",
    tip: "Highway riding between Bahadurgarh and Delhi increases tyre and brake wear significantly — inspect monthly.",
    landmarks: ["Tikri Border", "NH-10 Highway", "Bahadurgarh City Centre", "Rohtak Road"],
    commonIssues: ["Tyre wear on highway", "Brake pad wear", "Dust filter clogging", "Suspension stress on rough patches"],
    priceNote: "Covers Bahadurgarh city and Tikri border area. Same pricing as Delhi NCR.",
    responseTime: "55-70 minutes from Delhi base",
  },
  "sonipat": {
    area: "Model Town, Sector 14, Murthal, GT Road",
    tip: "GT Road heavy truck traffic in Sonipat means frequent brake pad and tyre checks are essential for safety.",
    landmarks: ["Murthal Dhabas", "GT Road", "Sonipat City Centre", "Kundli Industrial Area"],
    commonIssues: ["Brake wear in heavy traffic", "Tyre damage from trucks", "Dust filter clogging", "Chain wear on highway"],
    priceNote: "Covers Sonipat city and Murthal corridor. Highway breakdown assistance available.",
    responseTime: "60-80 minutes from Delhi base",
  },
  "rohtak": {
    area: "Civil Lines, Sector 1, Delhi Road, Model Town",
    tip: "Dry Haryana weather in Rohtak demands regular chain lubrication every 400km to prevent premature wear.",
    landmarks: ["PGIMS Hospital Road", "Delhi Road", "Rohtak City Centre", "Asthal Bohar Chowk"],
    commonIssues: ["Chain wear in dry conditions", "Air filter dust clogging", "Tyre pressure loss", "Battery issues in winter"],
    priceNote: "Rohtak city full coverage. Delhi Road corridor pickups on same day.",
    responseTime: "65-85 minutes from Delhi base",
  },
  "panipat": {
    area: "Model Town, GT Road, Sector 12, Panipat Refinery Road",
    tip: "Industrial and refinery pollution in Panipat clogs air filters faster than average — inspect every 1000km.",
    landmarks: ["Panipat Refinery", "GT Road", "Model Town", "Kala Amb"],
    commonIssues: ["Air filter clogging from pollution", "Engine oil degradation", "Rust from chemical air", "Tyre wear on industrial roads"],
    priceNote: "Panipat city and refinery area coverage. Industrial pickup slots available.",
    responseTime: "70-90 minutes from Delhi base",
  },
  "karnal": {
    area: "Sector 6, Model Town, GT Road, Karnal City",
    tip: "Long highway rides from Karnal to Delhi stress engine oil faster — consider oil changes every 2500km.",
    landmarks: ["GT Road Karnal", "Karan Lake", "Sector 6 Market", "NH-44"],
    commonIssues: ["Engine oil degradation on highway", "Tyre wear at highway speed", "Brake stress on long rides", "Battery drain in winter"],
    priceNote: "Karnal city coverage. Highway corridor service available on request.",
    responseTime: "75-95 minutes from Delhi base",
  },
  "rewari": {
    area: "Rewari City, Dharuhera, Bawal, NH-11",
    tip: "Industrial zone dust in Rewari and Dharuhera requires air filter checks every 1500km minimum.",
    landmarks: ["Dharuhera Industrial Area", "NH-11", "Rewari City Centre", "Bawal HSIIDC"],
    commonIssues: ["Air filter clogging", "Chain rust from dust", "Tyre punctures on industrial roads", "Overheating in summer"],
    priceNote: "Covers Rewari, Dharuhera, and Bawal industrial belt. Factory worker slots available.",
    responseTime: "65-80 minutes from Gurgaon base",
  },
  "bhiwadi": {
    area: "RIICO Industrial Area, Bhiwadi City, Tapukara, Khushkhera",
    tip: "Factory dust in Bhiwadi's RIICO zone is extremely fine and penetrates air filters quickly — replace every 1200km.",
    landmarks: ["RIICO Industrial Area", "Bhiwadi City Centre", "Tapukara Industrial Zone", "NH-48 Bhiwadi Exit"],
    commonIssues: ["Fine dust air filter damage", "Engine overheating", "Chain and sprocket wear", "Electrical issues from dust"],
    priceNote: "Industrial area specialist in Bhiwadi. RIICO zone pickup available all days.",
    responseTime: "60-75 minutes from Gurgaon base",
  },
  "alwar": {
    area: "Alwar City, Behror, Tijara, NH-48",
    tip: "Rocky Aravalli terrain around Alwar puts extra stress on suspension and tyres — inspect every 3000km.",
    landmarks: ["Alwar Fort", "Siliserh Lake", "Behror on NH-48", "Tijara Fort"],
    commonIssues: ["Suspension damage on rocky roads", "Tyre sidewall cuts", "Chain wear", "Brake stress on hilly terrain"],
    priceNote: "Alwar city and Behror NH-48 corridor coverage. Hillside pickup available.",
    responseTime: "70-90 minutes from Gurgaon base",
  },
  "meerut": {
    area: "Garh Road, Pallavpuram, Shastri Nagar, Hapur Road",
    tip: "Heavy congestion in Meerut city centre accelerates clutch and brake wear — inspect both every 5000km.",
    landmarks: ["Meerut Cantonment", "Hapur Road", "Garh Road", "Shastri Nagar Market"],
    commonIssues: ["Clutch wear in traffic", "Brake pad wear", "Air filter dust clogging", "Tyre punctures on crowded roads"],
    priceNote: "Meerut city full coverage. Cantonment and Hapur Road pickups available.",
    responseTime: "60-80 minutes from Noida base",
  },
  "hapur": {
    area: "Hapur City, Pilkhuwa, Garh Mukteshwar, NH-9",
    tip: "Dusty NH-9 stretch through Hapur is notorious for air filter damage — service every 1000km on this route.",
    landmarks: ["NH-9 Hapur Bypass", "Pilkhuwa Market", "Garh Mukteshwar Ghat", "Hapur City Centre"],
    commonIssues: ["Air filter damage on NH-9", "Chain dust accumulation", "Tyre wear", "Suspension stress"],
    priceNote: "Covers Hapur city and NH-9 corridor. Breakdown assistance available on highway.",
    responseTime: "65-80 minutes from Noida base",
  },
  "bulandshahr": {
    area: "Bulandshahr City, Khurja, Sikandrabad, NH-34",
    tip: "Rural roads around Bulandshahr are tough on suspension — get a full suspension check every 3000km.",
    landmarks: ["Bulandshahr City Centre", "Khurja Pottery Market", "Sikandrabad", "NH-34"],
    commonIssues: ["Suspension damage on rural roads", "Tyre punctures", "Chain wear", "Dust filter clogging"],
    priceNote: "Covers Bulandshahr, Khurja, and Sikandrabad. Rural road pickup available.",
    responseTime: "70-85 minutes from Noida base",
  },
  "modinagar": {
    area: "Modinagar City, Muradnagar, Modi Nagar Industrial Area",
    tip: "Industrial air quality in Modinagar demands more frequent oil and filter changes — every 2000km recommended.",
    landmarks: ["Modinagar Industrial Area", "Muradnagar", "NH-58", "Modi Mills"],
    commonIssues: ["Oil contamination from industrial air", "Air filter clogging", "Chain rust", "Battery wear"],
    priceNote: "Covers Modinagar and Muradnagar. Industrial zone pickup available weekdays.",
    responseTime: "55-70 minutes from Noida base",
  },
  "mumbai": {
    area: "Andheri, Bandra, Thane, Navi Mumbai, Borivali",
    tip: "Mumbai's coastal salt air causes chain and sprocket rust within weeks — lubricate chain every 200-300km.",
    landmarks: ["Bandra-Worli Sea Link", "Andheri Station", "Thane Creek", "Vashi Bridge"],
    commonIssues: ["Salt corrosion on chain and sprockets", "Electrical short circuits in monsoon flooding", "Waterlogged brake failure", "Rust on exposed metal parts"],
    priceNote: "Covers Western, Central, and Harbour line corridors. Navi Mumbai covered with no surcharge.",
    responseTime: "60-90 minutes depending on Mumbai traffic",
  },
  "bangalore": {
    area: "Whitefield, Koramangala, HSR Layout, Indiranagar, Electronic City",
    tip: "Bangalore's flyovers and long uphill stretches stress clutch plates — inspect every 7000km in city riding.",
    landmarks: ["Silk Board Junction", "Electronic City Flyover", "Whitefield IT Corridor", "Indiranagar 100ft Road"],
    commonIssues: ["Clutch plate wear on flyovers", "Pothole suspension damage", "Air filter clogging from construction dust", "Battery drain in traffic"],
    priceNote: "Full coverage across Bangalore. Tech park pickup slots available for IT professionals.",
    responseTime: "50-75 minutes across Bangalore",
  },
  "hyderabad": {
    area: "Gachibowli, HITEC City, Banjara Hills, Secunderabad, Kukatpally",
    tip: "Hyderabad summer temperatures above 42°C degrade engine oil rapidly — change oil every 2000km in summer.",
    landmarks: ["HITEC City", "Hussain Sagar Lake", "Secunderabad Station", "Gachibowli Stadium"],
    commonIssues: ["Engine oil degradation in heat", "Tyre blowouts in summer", "Battery failure in heat", "Air filter dust clogging"],
    priceNote: "Covers HITEC City, Gachibowli, and Old City. IT corridor priority slots available.",
    responseTime: "50-70 minutes across Hyderabad",
  },
  "chennai": {
    area: "Anna Nagar, T. Nagar, OMR, Velachery, Adyar",
    tip: "Chennai's coastal humidity accelerates chain rusting — clean and lubricate every 300km during monsoon season.",
    landmarks: ["Marina Beach Road", "OMR IT Corridor", "T. Nagar Shopping District", "Chennai Port"],
    commonIssues: ["Chain and sprocket rust from humidity", "Electrical corrosion", "Tyre wear on OMR", "Air filter salt damage"],
    priceNote: "Full Chennai coverage including OMR and Old Mahabalipuram Road corridor.",
    responseTime: "55-75 minutes across Chennai",
  },
  "kolkata": {
    area: "Salt Lake, New Town, Park Street, Howrah, Ballygunge",
    tip: "Kolkata monsoon flooding regularly submerges roads — always inspect electrical systems and brakes after riding through floods.",
    landmarks: ["Howrah Bridge", "Salt Lake Sector V", "New Town Eco Park", "Park Street"],
    commonIssues: ["Electrical damage from monsoon flooding", "Brake failure after waterlogging", "Rust on chassis", "Tyre damage on tram tracks"],
    priceNote: "Covers Kolkata, Howrah, Salt Lake, and New Town. Monsoon emergency service available.",
    responseTime: "55-80 minutes across Kolkata",
  },
  "pune": {
    area: "Hinjewadi, Kothrud, Viman Nagar, Hadapsar, Wakad",
    tip: "Pune's ghat roads to Mumbai put extreme stress on brakes and clutch — get both inspected before and after ghat travel.",
    landmarks: ["Hinjewadi IT Park", "Wakad Bridge", "Viman Nagar Airport Road", "Sinhagad Road"],
    commonIssues: ["Brake wear on ghat roads", "Clutch stress on inclines", "Suspension damage on Pune roads", "Air filter clogging from construction"],
    priceNote: "Full Pune coverage including Hinjewadi and Pimpri-Chinchwad. IT park pickup available.",
    responseTime: "50-70 minutes across Pune",
  },
  "ahmedabad": {
    area: "SG Road, Prahlad Nagar, Navrangpura, Satellite, Bopal",
    tip: "Ahmedabad summer regularly hits 47°C — use 20W-50 high-grade engine oil from April to July.",
    landmarks: ["SG Road", "Sabarmati Riverfront", "GIFT City", "Prahlad Nagar Garden"],
    commonIssues: ["Engine oil breakdown in extreme heat", "Tyre blowouts on hot roads", "Battery failure in summer", "Rubber seal degradation"],
    priceNote: "Full Ahmedabad coverage. GIFT City and SG Road corridor priority service available.",
    responseTime: "50-65 minutes across Ahmedabad",
  },
  "surat": {
    area: "Adajan, Vesu, Athwa, Udhna, Ring Road",
    tip: "Surat's textile industry traffic creates constant stop-start conditions — clutch plates need inspection every 6000km.",
    landmarks: ["Diamond Bourse", "Surat Textile Market", "Tapi River Bridge", "Vesu Residential Area"],
    commonIssues: ["Clutch wear in stop-start traffic", "Air filter clogging from textile dust", "Chain wear", "Overheating in congestion"],
    priceNote: "Full Surat coverage including Diamond Bourse and textile market areas.",
    responseTime: "50-65 minutes across Surat",
  },
  "jaipur": {
    area: "Malviya Nagar, Vaishali Nagar, C-Scheme, Mansarovar, Tonk Road",
    tip: "Rajasthan desert sand is extremely abrasive — clean air filter every 800-1000km and use sealed chain lubricant.",
    landmarks: ["Hawa Mahal", "Malviya Nagar Market", "Tonk Road", "Mansarovar Metro"],
    commonIssues: ["Air filter sand clogging", "Chain and sprocket abrasion", "Tyre sidewall cracking in heat", "Engine overheating in summer"],
    priceNote: "Full Jaipur coverage. Walled City and outskirt areas covered with no surcharge.",
    responseTime: "50-70 minutes across Jaipur",
  },
  "lucknow": {
    area: "Gomti Nagar, Hazratganj, Aliganj, Indira Nagar, Mahanagar",
    tip: "Lucknow winters drop below 5°C — engine oil thickens significantly, always warm up for 3-5 minutes before riding.",
    landmarks: ["Hazratganj Market", "Gomti Nagar Extension", "Shaheed Path", "Lucknow Airport Road"],
    commonIssues: ["Engine oil thickening in winter", "Battery failure in cold", "Tyre pressure drop in winter", "Chain rust in fog season"],
    priceNote: "Full Lucknow coverage including Shaheed Path corridor and outskirts.",
    responseTime: "50-70 minutes across Lucknow",
  },
  "kanpur": {
    area: "Kakadeo, Civil Lines, Kidwai Nagar, Kalyanpur, GT Road",
    tip: "Industrial smoke and tannery pollution in Kanpur clogs air filters faster than most cities — clean every 1000km.",
    landmarks: ["Kanpur Cantonment", "GT Road", "Z Square Mall", "Bithoor Road"],
    commonIssues: ["Air filter damage from industrial smoke", "Engine oil contamination", "Chain rust from chemical air", "Tyre wear on GT Road"],
    priceNote: "Full Kanpur coverage including industrial and cantonment areas.",
    responseTime: "60-80 minutes across Kanpur",
  },
  "nagpur": {
    area: "Dharampeth, Sitabuldi, Wardha Road, Amravati Road, Hingna",
    tip: "Nagpur is India's hottest city with temperatures reaching 48°C — use synthetic engine oil and check coolant monthly in summer.",
    landmarks: ["Zero Mile Stone", "Wardha Road IT Park", "Ambazari Lake", "Hingna Industrial Area"],
    commonIssues: ["Engine overheating in extreme heat", "Coolant loss", "Tyre blowouts on hot roads", "Battery failure in heat"],
    priceNote: "Full Nagpur coverage. Wardha Road IT corridor and Hingna industrial area covered.",
    responseTime: "50-65 minutes across Nagpur",
  },
  "indore": {
    area: "Vijay Nagar, Palasia, AB Road, Scheme 54, Super Corridor",
    tip: "Indore's fast-moving traffic on AB Road increases tyre pressure loss — check tyre pressure every week.",
    landmarks: ["Rajwada Palace", "AB Road", "Super Corridor IT Park", "Vijay Nagar Square"],
    commonIssues: ["Tyre pressure loss at speed", "Brake wear on AB Road", "Air filter dust clogging", "Chain wear in traffic"],
    priceNote: "Full Indore coverage including Super Corridor and AB Road. IT park pickup available.",
    responseTime: "50-65 minutes across Indore",
  },
  "bhopal": {
    area: "Hoshangabad Road, MP Nagar, Arera Colony, Kolar Road",
    tip: "Bhopal's hilly terrain stresses brakes heavily on downhill stretches — inspect brake pads every month.",
    landmarks: ["Upper Lake", "MP Nagar Market", "Hoshangabad Road", "New Market"],
    commonIssues: ["Brake wear on hills", "Clutch stress on inclines", "Suspension damage on hilly roads", "Chain slipping on slopes"],
    priceNote: "Full Bhopal coverage including hilly areas and lake district.",
    responseTime: "50-70 minutes across Bhopal",
  },
  "patna": {
    area: "Boring Road, Patliputra, Kankarbagh, Rajendra Nagar, Bailey Road",
    tip: "Patna's flood-prone roads during monsoon damage wheel bearings and electrical systems — inspect both after every flood season.",
    landmarks: ["Gandhi Maidan", "Bailey Road", "Patliputra Colony", "Patna Junction"],
    commonIssues: ["Wheel bearing damage from waterlogging", "Electrical system corrosion", "Chain rust in monsoon", "Brake failure after flooding"],
    priceNote: "Full Patna coverage. Monsoon emergency service and post-flood inspection available.",
    responseTime: "50-70 minutes across Patna",
  },
  "vadodara": {
    area: "Alkapuri, Gotri, Manjalpur, Fatehgunj, Waghodia Road",
    tip: "Vadodara's industrial air from Petrochemicals complex degrades rubber seals and O-rings — inspect every 5000km.",
    landmarks: ["Laxmi Vilas Palace", "Waghodia Road Industrial Area", "Alkapuri Market", "GIDC Vadodara"],
    commonIssues: ["Rubber seal degradation from chemical air", "O-ring damage", "Air filter chemical clogging", "Engine oil contamination"],
    priceNote: "Full Vadodara coverage including GIDC and Waghodia Road industrial belt.",
    responseTime: "50-65 minutes across Vadodara",
  },
  "ludhiana": {
    area: "Model Town, Sarabha Nagar, BRS Nagar, Dugri, Ferozepur Road",
    tip: "Punjab winters in Ludhiana can drop below 2°C — battery capacity drops 30-40% in cold, get it tested before November.",
    landmarks: ["Ludhiana Railway Station", "Ferozepur Road", "Model Town Market", "Punjab Agricultural University"],
    commonIssues: ["Battery failure in winter", "Engine oil thickening in cold", "Tyre pressure drop", "Chain stiffening in cold weather"],
    priceNote: "Full Ludhiana coverage. Winter emergency battery service available.",
    responseTime: "50-65 minutes across Ludhiana",
  },
  "agra": {
    area: "Fatehabad Road, Sikandra, Civil Lines, Shahganj, NH-19",
    tip: "Agra's tourist traffic and rough inner-city roads cause uneven tyre wear — rotate tyres every 5000km.",
    landmarks: ["Taj Mahal Road", "Fatehabad Road", "Sikandra", "Agra Cantonment"],
    commonIssues: ["Uneven tyre wear in tourist traffic", "Suspension damage on rough roads", "Air filter dust clogging", "Chain wear in stop-start traffic"],
    priceNote: "Full Agra coverage including tourist zones and cantonment area.",
    responseTime: "50-70 minutes across Agra",
  },
  "nashik": {
    area: "Gangapur Road, College Road, Cidco, Satpur, Ambad",
    tip: "Nashik's sharp winding roads to vineyards and ghats put heavy stress on brakes — inspect brake pads every 4000km.",
    landmarks: ["Panchvati", "Gangapur Dam Road", "Ambad Industrial Area", "Nashik Road Station"],
    commonIssues: ["Brake wear on winding roads", "Clutch stress on ghat routes", "Suspension damage", "Tyre wear on sharp turns"],
    priceNote: "Full Nashik coverage including Ambad industrial area and Gangapur corridor.",
    responseTime: "50-65 minutes across Nashik",
  },
  "ranchi": {
    area: "Harmu, Lalpur, Kanke Road, Morabadi, Doranda",
    tip: "Jharkhand's rocky hilly roads around Ranchi demand monthly brake and suspension checks — don't skip them.",
    landmarks: ["Ranchi Lake", "Kanke Road", "Morabadi Ground", "Ranchi Railway Station"],
    commonIssues: ["Suspension damage on rocky roads", "Brake wear on hills", "Tyre sidewall cuts", "Chain slipping on inclines"],
    priceNote: "Full Ranchi coverage including hillside areas and Kanke Road.",
    responseTime: "50-70 minutes across Ranchi",
  },
  "coimbatore": {
    area: "RS Puram, Saibaba Colony, Peelamedu, Gandhipuram, Hopes College",
    tip: "Nilgiri foothills routes from Coimbatore to Ooty put extreme downhill stress on brakes — inspect before every ghat trip.",
    landmarks: ["Gandhipuram Bus Stand", "Peelamedu Airport Road", "RS Puram Market", "Brookefields Mall"],
    commonIssues: ["Brake wear on ghat routes", "Clutch stress on Nilgiri climbs", "Tyre wear on mountain roads", "Engine overheating on inclines"],
    priceNote: "Full Coimbatore coverage. Ghat route pre-inspection service available.",
    responseTime: "50-65 minutes across Coimbatore",
  },
  "vijayawada": {
    area: "Benz Circle, MG Road, Governorpet, Patamata, Vijayawada Bypass",
    tip: "Krishna riverbed dust near Vijayawada is fine and penetrating — clean air filter every 1200-1500km.",
    landmarks: ["Benz Circle", "Krishna River Bridge", "Prakasam Barrage", "Vijayawada Railway Station"],
    commonIssues: ["Air filter river dust clogging", "Chain rust near river", "Tyre wear on bypass roads", "Engine dust contamination"],
    priceNote: "Full Vijayawada coverage including bypass and riverfront areas.",
    responseTime: "50-65 minutes across Vijayawada",
  },
  "mysore": {
    area: "Vijayanagar, Kuvempunagar, Jayalakshmipuram, Hebbal, Mysore Road",
    tip: "Mysore palace road and tourist weekend traffic create stop-start conditions — check chain tension and clutch every 5000km.",
    landmarks: ["Mysore Palace", "Chamundi Hills", "Mysore Road", "Hebbal Industrial Area"],
    commonIssues: ["Chain slack in tourist traffic", "Clutch wear on Chamundi Hill", "Tyre wear on tourist roads", "Brake stress on hill descents"],
    priceNote: "Full Mysore coverage including palace road and Chamundi Hills area.",
    responseTime: "50-65 minutes across Mysore",
  },
  "jodhpur": {
    area: "Ratanada, Paota, Shastri Nagar, Sardarpura, Residency Road",
    tip: "Jodhpur desert sand is the most abrasive in India — clean air filter every 700-800km and use sealed chain.",
    landmarks: ["Mehrangarh Fort", "Clock Tower Market", "Residency Road", "Jodhpur Airport Road"],
    commonIssues: ["Severe air filter sand damage", "Chain and sprocket abrasion", "Tyre sidewall cracking in heat", "Fuel system sand contamination"],
    priceNote: "Full Jodhpur coverage. Desert condition specialist service available.",
    responseTime: "50-70 minutes across Jodhpur",
  },
  "raipur": {
    area: "Shankar Nagar, Telibandha, Pandri, Devendra Nagar, GE Road",
    tip: "Chhattisgarh heat and mining industry dust in Raipur demand more frequent oil and filter changes — every 1500km.",
    landmarks: ["GE Road", "Telibandha Lake", "Raipur Railway Station", "Shankar Nagar Market"],
    commonIssues: ["Air filter mining dust damage", "Engine oil contamination", "Chain rust", "Tyre wear on industrial roads"],
    priceNote: "Full Raipur coverage including GE Road corridor and industrial areas.",
    responseTime: "50-65 minutes across Raipur",
  },
  "kochi": {
    area: "Kakkanad, Edapally, MG Road, Aluva, Ernakulam",
    tip: "Kerala's year-round humidity causes chain rust within 200-300km — lubricate with waterproof chain lube every 250km.",
    landmarks: ["Marine Drive", "Edapally Junction", "Kakkanad IT Park", "Aluva Bridge"],
    commonIssues: ["Chain rusting from humidity", "Electrical corrosion", "Brake fluid moisture absorption", "Tyre sidewall mold in monsoon"],
    priceNote: "Full Kochi coverage including Kakkanad IT Park and Aluva. Monsoon service available.",
    responseTime: "50-70 minutes across Kochi",
  },
  "chandigarh": {
    area: "Sector 17, Sector 35, Sector 43, Mohali, Panchkula",
    tip: "Chandigarh's wide straight roads encourage higher speeds — check tyre pressure weekly and inspect tyres for wear.",
    landmarks: ["Rock Garden", "Sector 17 Plaza", "Mohali IT Park", "Sukhna Lake Road"],
    commonIssues: ["Tyre wear at highway speeds", "Brake fade at speed", "Chain stretch", "Battery drain in Himalayan winters"],
    priceNote: "Covers Chandigarh, Mohali, and Panchkula tri-city area with no extra charge.",
    responseTime: "45-60 minutes across tri-city area",
  },
  "bhubaneswar": {
    area: "Saheed Nagar, Patia, Nayapalli, Unit 4, Infocity",
    tip: "Odisha coastal air causes rust on exposed metal parts — apply anti-rust treatment to chassis every 6 months.",
    landmarks: ["Infocity IT Park", "Lingaraj Temple Road", "Patia Square", "Bhubaneswar Airport Road"],
    commonIssues: ["Chassis and metal rusting", "Chain corrosion", "Electrical connector corrosion", "Tyre damage in monsoon"],
    priceNote: "Full Bhubaneswar coverage including Infocity IT corridor.",
    responseTime: "50-65 minutes across Bhubaneswar",
  },
  "thiruvananthapuram": {
    area: "Kowdiar, Pattom, Kesavadasapuram, Vellayambalam, Technopark",
    tip: "Kerala monsoon and hilly terrain around Thiruvananthapuram stress both brakes and electrical systems — inspect after every monsoon month.",
    landmarks: ["Technopark IT Campus", "Kovalam Road", "Pattom Junction", "Thiruvananthapuram Central Station"],
    commonIssues: ["Brake wear on hilly roads", "Electrical corrosion in rain", "Chain rust in humidity", "Tyre wear on coastal roads"],
    priceNote: "Full Thiruvananthapuram coverage including Technopark and coastal areas.",
    responseTime: "50-70 minutes across Thiruvananthapuram",
  },
  "visakhapatnam": {
    area: "MVP Colony, Gajuwaka, Seethammadhara, Rushikonda, Steel Plant Area",
    tip: "Vizag sea breeze carries salt particles that cause rapid chain corrosion — wash bike weekly and lubricate chain every 250km.",
    landmarks: ["RK Beach Road", "Steel Plant Area", "Rushikonda Beach", "Gajuwaka Industrial Zone"],
    commonIssues: ["Salt corrosion on chain and metal", "Electrical connector rust", "Tyre sidewall cracking", "Brake rust in sea air"],
    priceNote: "Full Visakhapatnam coverage including Steel Plant and Rushikonda areas.",
    responseTime: "50-70 minutes across Visakhapatnam",
  },
  "madurai": {
    area: "Anna Nagar, KK Nagar, Thirunagar, Tallakulam, Bypass Road",
    tip: "Tamil Nadu summer in Madurai is extreme at 42°C+ — engine oil breaks down faster, change every 1500-2000km in summer.",
    landmarks: ["Meenakshi Temple Road", "Bypass Road", "Anna Nagar Market", "Madurai Airport Road"],
    commonIssues: ["Engine oil breakdown in heat", "Tyre blowouts on hot roads", "Battery failure in summer", "Fuel evaporation issues"],
    priceNote: "Full Madurai coverage including temple city area and bypass road.",
    responseTime: "50-65 minutes across Madurai",
  },
};