export const cities = [
  'delhi',
  'noida',
  'gurgaon',
  'faridabad',
  'ghaziabad',
  'greater-noida',
  'dwarka',
  'rohini',
  'pitampura',
  'janakpuri',
  'lajpat-nagar',
  'mumbai',
  'bangalore',
  'hyderabad',
  'chennai',
  'pune',
  'kolkata',
  'ahmedabad',
  'jaipur',
  'patna' , 
];

export interface CityContent {
  area: string;
  landmarks: string[];
  commonIssues: string[];
  priceNote: string;
  responseTime: string;
}

export const cityContent: Record<string, CityContent> = {
  delhi: {
    area: "South Delhi, West Delhi, East Delhi, Central Delhi",
    landmarks: ["Connaught Place", "Lajpat Nagar", "Karol Bagh"],
    commonIssues: [
      "Battery drain from Delhi's extreme summer heat cycles",
      "Suspension damage from flyover speed breakers",
      "AC cooling loss due to dust-clogged cabin filters",
      "Engine overheating in prolonged stop-and-go traffic",
    ],
    priceNote: "Prices in Delhi are fixed and transparent — what you see is what you pay, with no add-ons after the job.",
    responseTime: "35–50 minutes",
  },
  noida: {
    area: "Sector 18, Sector 62, Sector 120, Sector 137",
    landmarks: ["Sector 18 Market", "Sector 62 IT Hub", "Atta Market"],
    commonIssues: [
      "Suspension drift from sector road speed humps",
      "Battery under-charge from short daily office commutes",
      "AC pressure loss from long open-lot parking in the sun",
      "Tyre pressure drop on high-speed expressway stretches",
    ],
    priceNote: "Transparent pricing for Noida — no surprise fees after the job is done.",
    responseTime: "40–55 minutes",
  },
  gurgaon: {
    area: "DLF Phase 1–5, Sohna Road, Cyber City, Golf Course Road",
    landmarks: ["Cyber Hub", "DLF Cyber City", "Sector 29 Market"],
    commonIssues: [
      "Brake wear from high-speed NH48 expressway driving",
      "Tyre degradation on Sohna Road gravel patches",
      "AC compressor stress from long daily highway commutes",
      "Transmission strain from sustained expressway speeds",
    ],
    priceNote: "Competitive pricing in Gurgaon — all costs communicated upfront before work begins.",
    responseTime: "40–60 minutes",
  },
  faridabad: {
    area: "NIT, Sector 15, Old Faridabad, BPTP Area",
    landmarks: ["Crown Interiorz Mall", "Sector 15 Market", "NHPC Chowk"],
    commonIssues: [
      "Engine filter clogging from industrial zone dust",
      "Paint damage from stone chips on truck-heavy routes",
      "Battery electrolyte loss in peak summer heat",
      "Underbody rust from flooded monsoon roads",
    ],
    priceNote: "Faridabad pricing is itemised — every part and labour charge is explained clearly.",
    responseTime: "45–60 minutes",
  },
  ghaziabad: {
    area: "Indirapuram, Vaishali, Raj Nagar, Kaushambi",
    landmarks: ["Shipra Mall", "Indirapuram Habitat Centre", "Raj Nagar Extension"],
    commonIssues: [
      "Clutch wear from heavy stop-and-go traffic congestion",
      "Underbody rust from monsoon waterlogging at underpasses",
      "Engine carbon deposits from incomplete combustion in traffic",
      "Rim damage from potholed internal sector roads",
    ],
    priceNote: "Honest pricing in Ghaziabad — we explain all charges before starting any work.",
    responseTime: "40–55 minutes",
  },
  "greater-noida": {
    area: "Omega, Alpha, Knowledge Park, Pari Chowk",
    landmarks: ["Pari Chowk", "Alpha Commercial Belt", "Knowledge Park II"],
    commonIssues: [
      "Tyre blowout risk from under-inflation on the expressway",
      "Coolant degradation from extended high-speed driving",
      "Battery under-charge from highway-only commute patterns",
      "Alignment drift from expressway entry and exit ramps",
    ],
    priceNote: "Transparent pricing for Greater Noida — long-drive areas deserve straightforward service costs.",
    responseTime: "50–70 minutes",
  },
  dwarka: {
    area: "Sector 10, Sector 12, Sector 21, Dwarka Expressway",
    landmarks: ["Sector 10 Market", "Dwarka Expressway", "Sector 21 Metro Station"],
    commonIssues: [
      "Suspension wear from repeated flyover ramp impacts",
      "Clutch strain from frequent gear changes on flyovers",
      "Tyre edge wear from sharp flyover lane turns",
      "AC stress from long Gurgaon expressway commutes",
    ],
    priceNote: "Dwarka pricing is fixed — no rounding up, no hidden extras at checkout.",
    responseTime: "35–50 minutes",
  },
  rohini: {
    area: "Sector 3, Sector 7, Sector 24, Rohini West",
    landmarks: ["Mangalam Place Mall", "Rohini Sector 24 Market", "Rithala Metro Station"],
    commonIssues: [
      "Clutch wear from dense residential colony traffic",
      "Battery drain in large society parking lots from parasitic loads",
      "Tyre pressure imbalance from frequent colony speed breakers",
      "Carbon buildup from repeated short-trip driving patterns",
    ],
    priceNote: "Rohini pricing is honest — we break down every item so you can verify before we start.",
    responseTime: "35–50 minutes",
  },
  pitampura: {
    area: "Pitampura Main Market, TV Tower Area, Shalimar Bagh, Kohat Enclave",
    landmarks: ["Pitampura TV Tower", "Shalimar Bagh Market", "Unity One Mall"],
    commonIssues: [
      "Power steering load from narrow market lane U-turns",
      "Rim stress from colony kerb mounting and tight parking",
      "AC filter clogging from heavy market area dust",
      "Brake wear from dense pedestrian and auto-rickshaw traffic",
    ],
    priceNote: "Clear upfront pricing in Pitampura — no add-ons once the job is agreed upon.",
    responseTime: "35–50 minutes",
  },
  janakpuri: {
    area: "District Centre, Block B, Janakpuri West, Uttam Nagar",
    landmarks: ["Janakpuri District Centre", "Janakpuri West Metro", "TDI Mall"],
    commonIssues: [
      "Engine idle heat buildup from District Centre congestion",
      "Suspension wear from speed breakers every 50 metres in colonies",
      "Battery drain from repeated short-trip parking cycles",
      "Alignment drift from mixed old-and-new road surfaces",
    ],
    priceNote: "Transparent pricing in Janakpuri — we give a full quote before touching the vehicle.",
    responseTime: "35–55 minutes",
  },
  "lajpat-nagar": {
    area: "Lajpat Nagar Central Market, Ring Road Zone, Andrews Ganj, Moolchand",
    landmarks: ["Lajpat Nagar Central Market", "Moolchand Metro Station", "Defence Colony Flyover"],
    commonIssues: [
      "Radiator overheating from prolonged market idling",
      "Door and panel dents from congested market parking",
      "Battery drain from constant delivery stop-start cycles",
      "Tyre sidewall damage from kerb rubbing in narrow market lanes",
    ],
    priceNote: "Lajpat Nagar pricing is transparent — zero surprises on your final bill.",
    responseTime: "40–55 minutes",
  },
  mumbai: {
    area: "Andheri, Bandra, Thane, Navi Mumbai, Dadar, Powai",
    landmarks: ["Bandra-Kurla Complex", "Andheri Station", "Phoenix Marketcity Kurla"],
    commonIssues: [
      "Severe underbody and brake rust from coastal salt air and monsoon flooding",
      "Engine misfires from waterlogged roads and hydrostatic lock risk",
      "AC cabin mould and musty smell from extreme humidity levels",
      "Battery terminal corrosion accelerated by saline sea breeze",
    ],
    priceNote: "Transparent Mumbai pricing — all charges quoted before work begins, no port-city markups.",
    responseTime: "45–65 minutes",
  },
  bangalore: {
    area: "Koramangala, Indiranagar, Whitefield, Electronic City, HSR Layout",
    landmarks: ["Koramangala Forum Mall", "Indiranagar 100 Feet Road", "Whitefield ITPL"],
    commonIssues: [
      "Suspension stress from Whitefield and Outer Ring Road pothole stretches",
      "Overheating in long tech-park traffic jams during peak hours",
      "Battery undercharge from very short daily office commute distances",
      "AC filter clogging from construction dust on Peripheral Ring Road",
    ],
    priceNote: "Bangalore pricing is itemised and upfront — no surprises at the end of the job.",
    responseTime: "40–60 minutes",
  },
  hyderabad: {
    area: "Hitech City, Gachibowli, Banjara Hills, Secunderabad, Kukatpally",
    landmarks: ["Hitech City Cyber Towers", "Banjara Hills Road No. 12", "IKEA Gachibowli"],
    commonIssues: [
      "Tyre pressure loss from extreme summer heat on ORR highway stretches",
      "AC compressor overload during Hyderabad's prolonged 40°C+ summers",
      "Underbody damage from rocky terrain in older Secunderabad lanes",
      "Engine oil degradation from stop-and-go Kukatpally corridor congestion",
    ],
    priceNote: "Hyderabad pricing is fixed upfront — what's quoted is what you pay, always.",
    responseTime: "40–60 minutes",
  },
  chennai: {
    area: "T. Nagar, Anna Nagar, OMR, Velachery, Adyar",
    landmarks: ["T. Nagar Pondy Bazaar", "Phoenix MarketCity Velachery", "OMR IT Corridor"],
    commonIssues: [
      "Severe rust and corrosion on underbody from Chennai's coastal humidity",
      "AC refrigerant loss faster than inland cities due to salt-laden air",
      "Radiator overheating in peak Chennai summer temperatures above 42°C",
      "Tyre cracking and sidewall degradation from hot asphalt in summer",
    ],
    priceNote: "Chennai pricing is transparent and honest — every rupee accounted for before we start.",
    responseTime: "45–65 minutes",
  },
  pune: {
    area: "Kothrud, Hinjewadi, Baner, Viman Nagar, Hadapsar",
    landmarks: ["Hinjewadi IT Park", "Koregaon Park", "Magarpatta Cybercity"],
    commonIssues: [
      "Brake wear from frequent descents and ascents on Pune's hilly terrain",
      "Clutch strain from gear-intensive driving on Sinhagad Road slopes",
      "Windshield chips from gravel on Expressway Mumbai-Pune stretch",
      "Suspension damage from unmaintained roads in older Peth areas",
    ],
    priceNote: "Pune pricing is clear from the start — no add-ons, no surprises at checkout.",
    responseTime: "40–55 minutes",
  },
  kolkata: {
    area: "Salt Lake, Park Street, New Town, Howrah, Dum Dum",
    landmarks: ["Salt Lake Sector V", "Park Street", "New Town Action Area"],
    commonIssues: [
      "Severe underbody rust from monsoon waterlogging in low-lying areas",
      "Electrical issues from humidity-induced connector corrosion",
      "Engine sludge buildup from short city commutes in dense traffic",
      "Tyre damage from tram tracks and uneven roads in older city zones",
    ],
    priceNote: "Kolkata pricing is straightforward — full cost breakdown before any work starts.",
    responseTime: "45–65 minutes",
  },
  ahmedabad: {
    area: "SG Highway, Satellite, Navrangpura, Prahlad Nagar, Maninagar",
    landmarks: ["SG Highway Galleria Mall", "Law Garden", "Prahlad Nagar Corporate Road"],
    commonIssues: [
      "Battery failure from extreme summer temperatures regularly crossing 45°C",
      "AC compressor burnout from near-constant use in Ahmedabad's long summers",
      "Engine coolant evaporation faster than other cities due to dry desert heat",
      "Tyre blowouts from super-heated road surfaces on SG Highway in May–June",
    ],
    priceNote: "Ahmedabad pricing is fixed and fair — all charges explained clearly upfront.",
    responseTime: "40–55 minutes",
  },
  jaipur: {
    area: "Malviya Nagar, Vaishali Nagar, C-Scheme, Mansarovar, Sitapura",
    landmarks: ["World Trade Park", "Pink City Bazaars", "Sitapura Industrial Area"],
    commonIssues: [
      "Sand and dust ingestion causing air filter and fuel injector issues",
      "AC refrigerant loss from desert heat and vibration on highway roads",
      "Paint oxidation and fading from intense UV radiation and sand blasting",
      "Battery electrolyte loss from Jaipur's summer temperatures near 46°C",
    ],
    priceNote: "Jaipur pricing is transparent — no hidden charges, Pink City guarantee.",
    responseTime: "40–60 minutes",
  },

  patna: {
    area: "Kankarbagh, Boring Road, Bailey Road, Patliputra Colony, Rajendra Nagar",
    landmarks: ["Kankarbagh Market", "Boring Road Crossing", "Rajendra Nagar Railway Station"],
    commonIssues: [
      "Battery drain from Patna's extreme summer heat and high humidity",
      "Engine overheating in stop-and-go traffic during monsoon season",
      "Tyre wear from uneven roads and frequent potholes in older city areas",
      "Underbody rust from Ganga plain monsoon waterlogging on low roads",
    ],
    priceNote: "Patna pricing is transparent — no hidden charges, just honest service.",
    responseTime: "40–55 minutes",
  },
};

// Unique tip per service per city — the #1 on-page SEO differentiator
export const serviceCityTips: Record<string, Record<string, string>> = {
  "mechanic-near-me": {
    delhi: "Delhi's extreme summer heat and winter fog stress every system — from battery to AC. Schedule a full health check before season changes.",
    noida: "Noida's tech corridor roads are smooth, but high office commute mileage means you should service every 5,000 km regardless of time.",
    gurgaon: "Gurgaon's NH48 expressway speeds mean brakes, tyres, and clutch wear out 20% faster than city-only driving — plan more frequent checks.",
    faridabad: "Faridabad's industrial zones carry more dust and grit, causing faster air filter and engine oil degradation between services.",
    ghaziabad: "Ghaziabad's heavy truck traffic and narrow lanes mean more minor dents, faster brake wear, and increased vibration on vehicle mounts.",
    "greater-noida": "Greater Noida's long expressway commutes are easy on city parts but hard on tyres and fuel systems — check both every 6,000 km.",
    dwarka: "Dwarka's flyover-heavy layout means frequent speed changes that stress the clutch, gearbox, and engine mounts more than flat city roads.",
    rohini: "Rohini's dense residential traffic creates frequent start-stop driving — tough on clutch plates, brake pads, and fuel injectors.",
    pitampura: "Pitampura's narrow market lanes and frequent U-turns put extra load on the power steering system and front tyre wear edges.",
    janakpuri: "Janakpuri's mixed roads — from wide blocks to tight market lanes — demand well-balanced suspension and regular alignment checks.",
    "lajpat-nagar": "Lajpat Nagar's chronic market congestion means engines idle at high temp with low airflow — coolant and radiator checks are essential.",
    mumbai: "Mumbai's coastal air corrodes brake lines and exhaust systems faster than inland cities — a full underbody check every monsoon is essential.",
    bangalore: "Bangalore's tech-park traffic sits vehicles for 2+ hours daily — idle heat and short trips degrade oil and battery faster than highway use.",
    hyderabad: "Hyderabad's summer temperatures are intense and long — a pre-summer multi-point check covering AC, coolant, and battery is a must each April.",
    chennai: "Chennai's salt air and humidity attack every metal surface — annual anti-rust treatment of the underbody can add years to your vehicle's life.",
    pune: "Pune's hilly terrain and expressway driving in the same commute create mixed stress — brakes, clutch, and tyres need more frequent attention here.",
    kolkata: "Kolkata's monsoon flooding is among the worst in India — check brakes, underbody, and electrical connectors thoroughly after every heavy rain.",
    ahmedabad: "Ahmedabad's summer heat above 45°C pushes every system to its limit — battery, AC, coolant, and tyres all need a pre-summer health check.",
    jaipur: "Jaipur's desert dust clogs air filters in weeks, not months — inspect and clean or replace the air filter every 3,000 km in peak dusty season.",
    patna: "Patna's extreme weather swings — from 45°C summers to monsoon waterlogging — mean a full multi-point check before each season change is essential.",
  },
  "bike-service": {
    delhi: "Delhi summer heat degrades engine oil faster in bikes — switch to a higher-viscosity oil before peak summer to protect the engine.",
    noida: "Noida's ongoing road expansion means bikes encounter fresh unpaved stretches — air filters clog up faster, check them monthly.",
    gurgaon: "Gurgaon's corporate campus parking means bikes sit in the sun for hours — check tyre pressure after every long parking session.",
    faridabad: "Faridabad's factory zones expose bikes to grease and grit — clean the chain and sprocket every fortnight to prevent early wear.",
    ghaziabad: "Ghaziabad's waterlogged roads in monsoon cause chain and stand rusting — apply chain lube and anti-rust spray after heavy rain.",
    "greater-noida": "Greater Noida's expressway speeds are unusually high for bikes — ensure brakes and tyres are rated for sustained high-speed riding.",
    dwarka: "Dwarka's wide roads tempt higher speeds; check front fork seals and tyre wear regularly if you commute on the Dwarka Expressway.",
    rohini: "Rohini's night market crowds mean bikes sit in congestion for hours — carburettor, idle jets, and spark plugs need more frequent checks.",
    pitampura: "Pitampura's uneven internal colony roads are tough on bike wheel rims and spoke tension — inspect for cracks every 3 months.",
    janakpuri: "Janakpuri's school-and-market mix creates heavy morning and evening peak traffic — clutch cable and lever pivot need checking each quarter.",
    "lajpat-nagar": "Lajpat Nagar's dense parking means bikes sit in tight spots — fuel cap tampering and handle damage are common, check locks every visit.",
    mumbai: "Mumbai's monsoon season is brutal on bike chains, sprockets, and brake cables — apply waterproof chain lube and check cables monthly in June–September.",
    bangalore: "Bangalore's variable weather — heavy rain then dry heat — causes tyre pressure to fluctuate significantly; check pressure every week.",
    hyderabad: "Hyderabad's long dry summers cause tyre rubber to harden and crack — inspect sidewalls for dry rot every 6 months.",
    chennai: "Chennai's coastal air corrodes bike exhausts and spokes fast — a weekly rinse with fresh water and monthly anti-rust spray extend bike life.",
    pune: "Pune's ghat roads outside the city are beautiful but punishing on brakes — inspect brake pads and cables before any long weekend ride.",
    kolkata: "Kolkata's waterlogged monsoon roads can seize brakes and rust chains overnight — always dry the bike and lube the chain after rain riding.",
    ahmedabad: "Ahmedabad's intense summer heat causes engine oil to thin rapidly in bikes — switch to a higher viscosity grade oil before April each year.",
    jaipur: "Jaipur's sand-laden winds block carburettor jets on older bikes — clean the carburettor every 2,000 km during and after the dry season.",
    patna: "Patna's waterlogged monsoon roads rust bike chains and stands rapidly — apply chain lube every 300–500 km and rinse the bike after every rain ride.",
  },
  "car-service": {
    delhi: "Delhi's summer can push engine temperatures beyond safe limits — ensure coolant is flushed and the thermostat is checked before May.",
    noida: "Noida's Expressway speed humps cause gradual alignment drift — get a wheel alignment check at every service to maintain straight handling.",
    gurgaon: "Gurgaon's NH48 high-speed stretch wears brake pads and tyres 20% faster — factor this into your service interval planning.",
    faridabad: "Faridabad's heavy truck roads scatter debris that damages windshields and bonnet paint — a front-end protection film is worth it here.",
    ghaziabad: "Ghaziabad's waterlogged underpasses in monsoon are a known hydrolocking risk for cars — avoid flooded roads to protect the engine.",
    "greater-noida": "Greater Noida's wide roads encourage fast acceleration, which increases fuel consumption and puts extra load on the automatic transmission.",
    dwarka: "Dwarka's underpass structures have height restrictions — check your antenna and roof rack clearance before driving through.",
    rohini: "Rohini's Sector 24 market road has notorious potholes — suspension and wheel alignment need checks every 6 months minimum.",
    pitampura: "Pitampura's TV tower area sees heavy daily footfall with two-wheelers — door dings from tight parking are extremely common.",
    janakpuri: "Janakpuri's District Centre sees constant traffic jams — long idling increases carbon deposits in the intake manifold over time.",
    "lajpat-nagar": "Lajpat Nagar market's narrow lanes and delivery vehicles make parking dents common — consider paint protection film on door edges.",
    mumbai: "Mumbai's humidity means cabin air has more moisture than most cities — AC evaporator coils develop mould faster; get a disinfectant flush annually.",
    bangalore: "Bangalore's cool mornings and warm afternoons mean the AC runs intermittently — check refrigerant levels and cabin filter every 10,000 km.",
    hyderabad: "Hyderabad's long summer demands AC run near-continuously — get a full AC service including compressor oil check before March each year.",
    chennai: "Chennai's summer heat starts in February and runs through June — ensure refrigerant is topped up and condenser fins are clean before February.",
    pune: "Pune's pleasant climate means the AC is used less, but refrigerant still degrades — check levels every 18 months regardless of usage.",
    kolkata: "Kolkata's high humidity makes AC more essential here than temperature alone suggests — dehumidifier function health matters as much as cooling.",
    ahmedabad: "Ahmedabad's 45°C+ summer is the harshest AC stress in India — replace cabin filter and check compressor belt before the summer peak.",
    jaipur: "Jaipur's dusty air clogs the AC condenser and cabin filter twice as fast as greener cities — inspect both every 5,000 km.",
    patna: "Patna's high humidity and dust levels clog cabin air filters much faster than drier cities — inspect and replace the cabin filter every 5,000 km.",
  },
  "car-ac-repair": {
    delhi: "Delhi summers regularly hit 45°C — your AC compressor runs at maximum capacity, so check refrigerant levels and belt tension every April.",
    noida: "Noida's glass-heavy IT buildings and open parking lots heat car interiors to 60°C — pre-cool with fresh refrigerant before summer starts.",
    gurgaon: "Gurgaon's Cyber City underground parking causes moisture buildup in AC systems — check for mould in vents and musty cabin smell.",
    faridabad: "Faridabad's dust-heavy air clogs AC cabin filters fast — replace every 6 months for consistently clean, cool airflow.",
    ghaziabad: "Ghaziabad's stop-and-go traffic keeps the AC running continuously — the compressor belt and clutch need annual inspection.",
    "greater-noida": "Greater Noida's longer drives at highway speed make consistent AC performance critical — ensure condenser fins are clean before summer.",
    dwarka: "Dwarka's proximity to Najafgarh wetlands increases cabin humidity — the AC dehumidifier function gets stressed more here than elsewhere.",
    rohini: "Rohini's wide grid layout means more open road driving, but summer heat is equally harsh — an AC gas top-up before May prevents mid-commute failures.",
    pitampura: "Pitampura's long signal waits mean cars idle with AC blasting — the compressor runs at full load; get it inspected every year.",
    janakpuri: "Janakpuri's older residential zones have many ageing cars — old condenser coils corrode faster and lose cooling efficiency by summer.",
    "lajpat-nagar": "Lajpat Nagar's packed shopping lanes mean windows stay up and AC runs constantly — check for refrigerant leaks before the summer peak.",
    mumbai: "Mumbai's humidity causes AC vents to develop mould and musty smell within a year — an evaporator coil cleaning annually is strongly recommended.",
    bangalore: "Bangalore's moderate climate means the AC compressor clutch engages and disengages frequently — check clutch clearance every 15,000 km.",
    hyderabad: "Hyderabad's dry heat during summers puts AC gas under pressure — a full refrigerant check and top-up before March prevents failures mid-summer.",
    chennai: "Chennai's salt air corrodes AC condenser coils faster than any inland city — rinse the condenser with fresh water after trips near the coast.",
    pune: "Pune's hill station drives cause rapid temperature changes — the AC expansion valve can wear faster; inspect it at every annual service.",
    kolkata: "Kolkata's monsoon humidity is extreme — an AC cabin filter change every 6 months in this city is more important than anywhere else.",
    ahmedabad: "Ahmedabad summers are the harshest test for any AC system — refrigerant, compressor, and condenser all need a check before April.",
    jaipur: "Jaipur's dusty desert air blocks AC condenser airflow fast — clean the condenser fins every 3 months during the dry season.",
    patna: "Patna's extreme summer heat and high humidity both stress the AC system — a full gas check, filter change, and compressor inspection every year is essential.",
  },
  "battery-replacement": {
    delhi: "Delhi heat in May–June discharges batteries 30% faster — test your battery in April before it fails mid-commute on a hot day.",
    noida: "Noida's tech offices run dashcams and ECUs overnight — battery drain from parasitic loads is more common here; get a draw test done.",
    gurgaon: "Gurgaon's corporate underground parking lots see cars idle for hours with electronics on — battery health check every 18 months is key.",
    faridabad: "Faridabad's extreme summer heat causes battery electrolyte to evaporate faster — check water levels monthly on non-sealed batteries.",
    ghaziabad: "Ghaziabad's winter fog brings cold cranking issues — ensure your battery's CCA rating is adequate for January morning starts.",
    "greater-noida": "Greater Noida's long highway drives keep the alternator charging well, but short city-only commuters often face chronically undercharged batteries.",
    dwarka: "Dwarka's residential zones see cars used only for short local errands — batteries don't fully recharge on short trips and fail early.",
    rohini: "Rohini's large housing societies often have cars parked unused for days — a monthly engine run or trickle charger prevents deep discharge.",
    pitampura: "Pitampura's market areas mean frequent engine starts and stops — battery terminals corrode faster from repeated heat and vibration cycles.",
    janakpuri: "Janakpuri's older residential sectors have many cars with original batteries past their 3-year life — proactive replacement avoids surprise failures.",
    "lajpat-nagar": "Lajpat Nagar shopkeepers often leave hazard lights on while parked for deliveries — one of the most common battery drain causes in this area.",
    mumbai: "Mumbai's salt air corrodes battery terminals faster than inland cities — clean terminals with baking soda solution every 6 months.",
    bangalore: "Bangalore's pleasant weather is easy on batteries, but many tech workers use dashcams 24/7 — check for parasitic drain every year.",
    hyderabad: "Hyderabad's summer heat above 42°C destroys battery cells quickly — test battery health each April before the peak season hits.",
    chennai: "Chennai's coastal humidity causes battery corrosion and electrolyte loss — inspect battery terminals and casing every 4 months.",
    pune: "Pune's hilly terrain means the alternator works harder on climbs — battery charge cycles are more intense; test health every 18 months.",
    kolkata: "Kolkata's monsoon waterlogging can submerge battery trays — inspect for water ingress and corrosion after every major flood event.",
    ahmedabad: "Ahmedabad's extreme summer heat is the single biggest cause of battery failure in India — replace any battery over 2.5 years old before summer.",
    jaipur: "Jaipur's desert nights get surprisingly cold — cold cranking amps (CCA) matter here; ensure your battery rating covers winter starts.",
    patna: "Patna's summer heat reaches 44°C and winters drop sharply — batteries here face one of the widest thermal stress ranges; test and replace proactively every 2.5 years.",
  },
  "tyre-wheel": {
    delhi: "Delhi's ring road speed bumps are abrupt and frequent — front tyre wear becomes uneven without regular rotation every 5,000 km.",
    noida: "Noida's sector roads look smooth but hide surface cracks — sidewall bulges develop silently and can burst at expressway speed.",
    gurgaon: "Gurgaon's Sohna Road and Golf Course Extension have sharp gravel patches — check for slow punctures after every off-expressway trip.",
    faridabad: "Faridabad's truck routes leave road debris that causes nail punctures — keep a tubeless repair kit in the boot at all times.",
    ghaziabad: "Ghaziabad's flooded monsoon roads hide potholes that bend rims — get wheel balancing and rim inspection after every wet season.",
    "greater-noida": "Greater Noida's expressway is long and fast — under-inflated tyres at high speed are the leading cause of blowouts; check pressure weekly.",
    dwarka: "Dwarka's flyover entry ramps have sharp angled turns — outer tyre edges wear faster, requiring rotation every 5,000 km without fail.",
    rohini: "Rohini's inner colony roads are narrow with hard kerb edges — avoid mounting pavements as it causes invisible rim cracks that fail later.",
    pitampura: "Pitampura's market area has constant delivery vehicles — shared narrow roads mean higher nail and glass puncture risk for parked cars.",
    janakpuri: "Janakpuri's residential blocks have speed breakers every 50 metres — constant impact on the same spot causes premature tyre cupping.",
    "lajpat-nagar": "Lajpat Nagar's packed market lanes mean slow-speed kerb rubbing — check tyre sidewalls for cuts and bubbles every month.",
    mumbai: "Mumbai's coastal expressways and pothole-heavy suburbs demand tyre checks every month — sidewall cracking from salt and heat is common.",
    bangalore: "Bangalore's ORR and Whitefield roads have uneven patching — tyre pressure and tread depth need monthly checks during construction seasons.",
    hyderabad: "Hyderabad's long ORR drives at speed require properly inflated tyres — check pressure weekly to prevent blowouts in summer heat.",
    chennai: "Chennai's hot asphalt in summer causes tyre rubber to soften and pick up road debris faster — inspect for embedded nails weekly.",
    pune: "Pune's ghat roads and expressway combine high speeds with sharp curves — tyre tread depth is safety-critical; check every 5,000 km.",
    kolkata: "Kolkata's monsoon floods hide potholes that can damage rims instantly — after any waterlogged drive, inspect rims and tyre beads.",
    ahmedabad: "Ahmedabad's sun-baked road surfaces heat tyres to dangerous levels in summer — always check pressure in the morning before the heat builds.",
    jaipur: "Jaipur's desert roads can be deceptively rough — sand and gravel embed in tyres causing slow punctures; inspect after every highway drive.",
    patna: "Patna's monsoon season hides deep potholes that damage rims and tyre sidewalls — after every waterlogged road, inspect both for cracks and bulges.",
  },
  "engine-repair": {
    delhi: "Delhi's summer heat causes engine oil to thin out rapidly — use 10W-40 or higher grade and change every 5,000 km without exception.",
    noida: "Noida's highway commuting can mask early engine knock — oil pressure and timing checks should be part of every scheduled service.",
    gurgaon: "Gurgaon's sustained high-speed driving puts turbos under constant strain on diesel vehicles — turbo oil feed pipes need annual inspection.",
    faridabad: "Faridabad's dust-heavy industrial air causes engine sludge buildup — a full engine flush every 15,000 km keeps internals clean.",
    ghaziabad: "Ghaziabad's stop-and-go traffic causes incomplete combustion — carbon deposits build up on intake valves faster than in other cities.",
    "greater-noida": "Greater Noida's expressway long runs are overall good for the engine, but coolant systems must still be flushed every 2 years.",
    dwarka: "Dwarka's flyover-heavy driving involves frequent gear shifts — engine mounts and transmission links wear faster than on flat city roads.",
    rohini: "Rohini's dense traffic means engines idle for long durations — increased oil degradation from heat soak without airflow shortens oil life.",
    pitampura: "Pitampura's constant braking and acceleration increases fuel injector fouling in petrol engines — a fuel system clean every 15,000 km helps.",
    janakpuri: "Janakpuri's older road network has more vibration — engine mounts and exhaust hangers wear out faster and need checking annually.",
    "lajpat-nagar": "Lajpat Nagar's chronic congestion forces engines to work in high-temp, low-airflow conditions — radiator flushing is critical every 2 years.",
    mumbai: "Mumbai's monsoon waterlogging risks hydrolock — if your engine stalls in a flooded road, do NOT restart it; call for a tow immediately.",
    bangalore: "Bangalore's long IT-park traffic jams keep engines idling for hours — carbon buildup on intake valves is a major issue; a fuel system clean every 15,000 km helps.",
    hyderabad: "Hyderabad's summer heat causes engine oil to break down faster — switch to fully synthetic oil and reduce change intervals to 5,000 km in peak summer.",
    chennai: "Chennai's coastal humidity causes engine metal components to corrode faster — use high-quality coolant with corrosion inhibitors and flush every 2 years.",
    pune: "Pune's ghat climbs put torque demand on engines that flat-city cars never experience — check engine mounts and exhaust gaskets annually.",
    kolkata: "Kolkata's monsoon water ingestion through low intakes is a real hydrolock risk — ensure your air intake is high and sealed before monsoon.",
    ahmedabad: "Ahmedabad's summer causes engine coolant to evaporate noticeably — check coolant level monthly from April to June and top up with the correct ratio.",
    jaipur: "Jaipur's dusty air causes air filters to clog rapidly, leading to rich fuel mixture and carbon deposits — inspect the air filter every 3,000 km.",
    patna: "Patna's monsoon waterlogging risk for engine hydrolock is high on low-lying roads — avoid driving in flooded areas and get the air intake inspected every monsoon.",
  },
  "denting-painting": {
    delhi: "Delhi's dense traffic makes door dings in market parking almost unavoidable — paint edge protection strips are a smart investment.",
    noida: "Noida's Sector 18 market area is notorious for parking lot scratches — protective film on side panels pays for itself quickly.",
    gurgaon: "Gurgaon's corporate valet parking occasionally causes minor scuffs — always document your car's condition before handing over keys.",
    faridabad: "Faridabad's industrial road stone chips leave bonnet and bumper paint chips — a front-end protection coating prevents early rust.",
    ghaziabad: "Ghaziabad's truck-heavy roads cause sand-blasting damage on lower body panels — treat stone chips early before rust sets in.",
    "greater-noida": "Greater Noida's active construction zones scatter loose gravel — stone chips on lower doors and sills are common and should be sealed promptly.",
    dwarka: "Dwarka's tight flyover exits create brush damage on side mirrors and bumpers — paint protection film adds years to the exterior finish.",
    rohini: "Rohini's crowded bus terminals and narrow lanes mean side mirrors get clipped regularly — check for stress cracks at the base housing.",
    pitampura: "Pitampura's delivery two-wheelers frequently brush parked cars — a regular wax coating slows paint oxidation from minor surface scratches.",
    janakpuri: "Janakpuri's residential clusters have cars parked bumper-to-bumper — reverse dents from parking are the most common repair here.",
    "lajpat-nagar": "Lajpat Nagar's courier vans and e-rickshaws compete for every lane inch — door edge protectors and rear bumper strips prevent repeated dents.",
    mumbai: "Mumbai's narrow lanes and heavy traffic cause frequent minor scrapes — a clear protective film on bumpers and door edges is worth every rupee.",
    bangalore: "Bangalore's tech-park valet services occasionally cause door dings — document your car before handing keys and address paint chips quickly before rust sets in.",
    hyderabad: "Hyderabad's flyover pillars and tight service roads cause low-speed pillar scrapes on front bumpers — check spacing carefully in pillar-lined areas.",
    chennai: "Chennai's salt air accelerates rust at any paint chip — treat all stone chips and scratches within weeks to prevent corrosion spreading.",
    pune: "Pune's gravel on mountain roads creates bonnet stone chips — a protective film on the bonnet leading edge prevents paint damage on highway drives.",
    kolkata: "Kolkata's tram tracks and potholes cause underside scrapes on low-clearance cars — check for paint damage and underbody scratches every monsoon.",
    ahmedabad: "Ahmedabad's intense UV radiation fades paint noticeably within 2–3 years — a ceramic coating or quality wax every 6 months extends colour life.",
    jaipur: "Jaipur's sand and grit act like sandpaper on paint at speed — a front-end paint protection film is especially valuable on highway-driven cars.",
    patna: "Patna's narrow inner-city roads and rickshaw congestion mean frequent minor dents — rubber door edge guards and a front bumper strip prevent the most common paint damage.",
  },
  "ev-service": {
    delhi: "Delhi's EV subsidy ecosystem is maturing fast — ensure your battery management system (BMS) is calibrated for Delhi's extreme summer heat.",
    noida: "Noida's growing charging infrastructure in Sectors 62 and 137 is great, but grid voltage fluctuations can stress onboard chargers over time.",
    gurgaon: "Gurgaon's long expressway distances test range anxiety on EVs — ensure battery cells are balanced for consistent and predictable range output.",
    faridabad: "Faridabad's heat and industrial air quality accelerate EV battery pack degradation — a cooling system inspection every 6 months is essential.",
    ghaziabad: "Ghaziabad's mixed road quality affects EV regenerative braking calibration — check regen sensitivity settings seasonally for optimal energy recovery.",
    "greater-noida": "Greater Noida's long, smooth expressway is ideal for EVs, but range estimates should account for AC load during peak Delhi NCR summers.",
    dwarka: "Dwarka is close to the IGI Airport EV charging corridor — great for long-range trips, but ensure your DC fast-charge port is clean and unseized.",
    rohini: "Rohini's growing EV two-wheeler adoption means more scooters on narrow colony roads — motor and controller health checks are increasingly needed.",
    pitampura: "Pitampura's market delivery riders often overload EV scooters with goods — motor temperature threshold checks every few months prevent burnout.",
    janakpuri: "Janakpuri sees many electric auto-rickshaws in the area — if you own one, battery terminal corrosion from monsoon humidity is the top issue.",
    "lajpat-nagar": "Lajpat Nagar's delivery EVs face constant fast charge-discharge cycles — a battery health monitor check every 3 months extends overall lifespan.",
    mumbai: "Mumbai's monsoon humidity can infiltrate EV charging ports — always use port covers and inspect the charge port seal before the rainy season.",
    bangalore: "Bangalore has India's best EV charging density — but grid fluctuations in older areas can stress onboard chargers; use a surge-protected outlet at home.",
    hyderabad: "Hyderabad's long summer stresses EV battery thermal management — ensure the battery cooling system is inspected every 6 months.",
    chennai: "Chennai's coastal salt air corrodes EV battery pack vents and motor housings — an annual corrosion inspection of the battery enclosure is recommended.",
    pune: "Pune's hilly terrain tests EV regenerative braking heavily — check regen brake calibration and motor health every 10,000 km.",
    kolkata: "Kolkata's monsoon flooding is a serious risk for EVs — avoid waterlogged roads and inspect battery tray seals after any flood exposure.",
    ahmedabad: "Ahmedabad's peak summer heat causes EV battery degradation at an accelerated rate — park in shade and avoid charging in full sunlight above 44°C.",
    jaipur: "Jaipur's dusty desert air blocks EV cooling vents — clean motor and battery cooling vent grilles every 2 months during dry season.",
    patna: "Patna's monsoon waterlogging is dangerous for EV battery enclosures — inspect battery tray seals and charge port covers before and after every monsoon season.",
  },
};
